---
  name: Build, Test, and Deploy
  on:
    push:
      branches:
        - main
    pull_request:
      branches:
        - main
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Maven
          uses: actions/setup-java@v1
          with:
            java-version: "17"
        - name: Build with Maven (compile phase only)
          run: >
            cd moduloInicioSesion/LoginBack/LoginBack
  
            mvn compile
            
            mvn clean package
        - name: deploy to azure
          uses: azure/webapps-deploy@v2
          with:
            app-name: 'cvds-app'
            publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
            package: /home/runner/work/moduloInicioSesion/LoginBack/LoginBack/target/gestortareasbackend-0.0.1-SNAPSHOT.jar
    test:
      needs: build
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Maven
          uses: actions/setup-java@v1
          with:
            java-version: "21"
        - name: Run tests with Maven (verify phase)
          run: >
            cd moduloInicioSesion/LoginBack/LoginBack
  
            mvn verify
    deploy:
      needs: test
      runs-on: ubuntu-latest
      steps:
        - name: Print deployment message
          run: echo "En construcción ..."
  